# Generated by Django 5.0.6 on 2025-06-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amr', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Body System Affected',
                'ordering': ['amr'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['demand'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['gender'],
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Chief of Complaint',
                'ordering': ['illness'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='MedicalServiceGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_given', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clinic_medicalservicegiven',
                'ordering': ['medical_given'],
            },
        ),
        migrations.CreateModel(
            name='MedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('clinic_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('critical', models.IntegerField(null=True)),
                ('consumed', models.IntegerField(default=0, null=True)),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.demand')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Clinic_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('amr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.amr')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.company')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.gender')),
                ('illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.illness')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location')),
                ('medcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.medcode')),
                ('medical_given', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.medicalservicegiven')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('clinic_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('critical', models.IntegerField(null=True)),
                ('consumed', models.IntegerField(default=0, null=True)),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.demand')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location')),
                ('medcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinic.medcode')),
            ],
            options={
                'ordering': ['medicine'],
            },
        ),
    ]
