# Generated by Django 5.0.6 on 2025-06-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medcode',
            options={'ordering': ['code'], 'verbose_name': 'Medicine List'},
        ),
        migrations.AlterField(
            model_name='medcode',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.demand'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.location'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='clinic.medcode'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MedicineMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('clinic_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location')),
            ],
            options={
                'ordering': ['-clinic_date_added'],
            },
        ),
    ]
