# Generated by Django 5.0.6 on 2025-03-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalServiceGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_given', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['medical_given'],
            },
        ),
        migrations.AddField(
            model_name='clinic_record',
            name='medical_given',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.medicalservicegiven'),
        ),
    ]
