# Generated by Django 5.0.6 on 2025-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_record',
            name='department',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='consumed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
