# Generated by Django 5.0.6 on 2025-03-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
    ]
