# Generated by Django 5.0.6 on 2025-02-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_record',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
