# Generated by Django 5.0.6 on 2025-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_clinic_record_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_record',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
