# Generated by Django 5.0.6 on 2025-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20250319_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='critical',
            field=models.IntegerField(null=True),
        ),
    ]
