# Generated by Django 5.0.6 on 2025-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicalservicegiven_clinic_record_medical_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_record',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
