# Generated by Django 5.0.6 on 2025-02-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_record_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_record',
            name='amr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.amr'),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.company'),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.department'),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.gender'),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.illness'),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinic_record',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.location'),
        ),
    ]
