# Generated by Django 5.0.6 on 2025-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinic_record_amr_alter_clinic_record_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic_record',
            options={'ordering': ['date_added']},
        ),
    ]
