# Generated by Django 5.0.6 on 2025-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinic_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic_record',
            options={},
        ),
    ]
