# Generated by Django 5.0.6 on 2025-03-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_clinic_record_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.medicine')),
            ],
            options={
                'ordering': ['medicine'],
            },
        ),
    ]
