# Generated by Django 5.0.6 on 2025-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_clinic_record_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_record',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
