# Generated by Django 5.0.6 on 2025-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_medicinenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='clinic_date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
