# Generated by Django 5.0.6 on 2024-10-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='demand_item',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
