# Generated by Django 5.0.6 on 2024-10-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcode',
            name='site',
        ),
    ]
