# Generated by Django 5.0.6 on 2024-10-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.teammember'),
        ),
    ]
