# Generated by Django 5.0.6 on 2024-10-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_itemcode_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
    ]
