# Generated by Django 5.0.6 on 2024-10-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_demand_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='demand_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.demanditems'),
        ),
    ]
