# Generated by Django 5.0.6 on 2024-10-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itembase_site_alter_item_floor_alter_item_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembase',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
    ]
