# Generated by Django 5.0.6 on 2024-10-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemcode_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.floor'),
        ),
    ]
