# Generated by Django 5.0.6 on 2024-10-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['member'], 'verbose_name_plural': 'Staff Name'},
        ),
    ]
