# Generated by Django 5.0.6 on 2024-10-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_floor_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='middleName',
        ),
        migrations.AddField(
            model_name='item',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.floor'),
        ),
        migrations.AddField(
            model_name='item',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
    ]
