# Generated by Django 5.0.6 on 2024-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_firstname_remove_item_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
