# Generated by Django 5.0.6 on 2024-10-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='department_name',
        ),
    ]
