# Generated by Django 5.0.1 on 2024-06-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_avatar_remove_user_bio_user_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
